# Templates for ci jobs - test cdash
# It defines workflow rules, templates to create docker images, to configure, build siconos and so on.
include:
   - ci_gitlab/gitlab-ci-siconos-templates.yml

# --- First, build docker images that contains all the required dependencies to build siconos ---
# This step is optional and run only when the commit message starts with "[docker-build]"
debian-bookworm:docker-build:
  variables:
    IMAGE_NAME: debian-bookworm
    SICONOS_DOCKER_TARGET: siconos-base-python
    RESULT_NAME: $SICONOS_REGISTRY/sources/debian-bookworm
  extends: .docker-build

fedora38:docker-build:
  variables:
    IMAGE_NAME: fedora-38
    SICONOS_DOCKER_TARGET: siconos-base-python
    RESULT_NAME: $SICONOS_REGISTRY/sources/fedora-38
  extends: .docker-build

ubuntu22.04:docker-build:
  variables:
    IMAGE_NAME: ubuntu22.04
    SICONOS_DOCKER_TARGET: siconos-base-python
    RESULT_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
  extends: .docker-build

image4doc:docker-build:
  variables:
    IMAGE_NAME: ubuntu22.04
    SICONOS_DOCKER_TARGET: siconos-base-doc
    RESULT_NAME: $SICONOS_REGISTRY/sources/image4doc
  extends: .docker-build
  stage: docker-build-layer2
  needs: ["ubuntu22.04:docker-build"]

opencascade:docker-build:
  variables:
    IMAGE_NAME: opencascade
    SICONOS_DOCKER_TARGET: mamba-occenv
    RESULT_NAME: $SICONOS_REGISTRY/sources/opencascade
  extends: .docker-build
  when: manual

# A specific image, that may be used to install siconos,
# get examples and provide some notebooks to
# run siconos software.
jupyter-notebook:docker-build:
  variables:
    IMAGE_NAME: jupyterlab
    SICONOS_DOCKER_TARGET: jupylab
    RESULT_NAME: $SICONOS_REGISTRY/sources/jupyterlab
  extends: .docker-build
  stage: docker-build-layer2
  needs: ["ubuntu22.04:docker-build"]

# The same, based on micromamba.
mambaenv:docker-build:
  variables:
    IMAGE_NAME: jupyterlab-mamba
    SICONOS_DOCKER_TARGET: mambaenv
    RESULT_NAME: $SICONOS_REGISTRY/sources/mambaenv
  extends: .docker-build
   
  
# Manual jobs, used to create docker images.
# docker-manual-img:
#   extends: .docker-rules
#   stage: docker-build-layer2
#   trigger:
#     include:
#       - ci_gitlab/docker-manual.yml


# -------------- Configure, build and test Siconos --------------

# -- Jobs that will always be executed (rule .devel-rules) --

# ------ ubuntu 22, debug setup -------
ubuntu22.04-debug:configure:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
    CDASH_SUBMIT: 1
    CONF_FILE: $SICONOS_CMAKE_CONF_PATH/siconos_devmode.cmake
  extends:
    - .siconos-configure
    - .devel-rules
  needs:
    - job: ubuntu22.04:docker-build
      optional: true

ubuntu22.04-debug:build:
  variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
      CDASH_SUBMIT: 1
  extends:
    - .siconos-build
    - .devel-rules
  needs: ["ubuntu22.04-debug:configure"]

ubuntu22.04-debug:test:
    variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
      CDASH_SUBMIT: 1
    extends:
      - .siconos-test
      - .devel-rules
    needs: ["ubuntu22.04-debug:build"]

# ------ ubuntu 22, default setup -------
ubuntu22.04-release:configure:
   variables:
     IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
     CDASH_SUBMIT: 1
   extends:
     - .siconos-configure
     - .devel-rules
   needs:
     - job: ubuntu22.04:docker-build
       optional: true

ubuntu22.04-release:build:
  variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
      CDASH_SUBMIT: 1
  extends:
    - .siconos-build
    - .devel-rules
  needs: ["ubuntu22.04-release:configure"]

ubuntu22.04-release:test:
    variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
      CDASH_SUBMIT: 1
    extends:
      - .siconos-test
      - .devel-rules
    needs: ["ubuntu22.04-release:build"]

# --- Siconos inside a notebook, default setup ---
mambalab:configure:
  variables:
     OPENBLAS_NUM_THREADS: 1
     IMAGE_NAME: $SICONOS_REGISTRY/sources/mambaenv
     CDASH_SUBMIT: 1
  extends:
    - .siconos-configure
    - .devel-rules
  needs:
    - job: mambaenv:docker-build
      optional: true


mambalab:build:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/mambaenv
    CDASH_SUBMIT: 1
  extends:
    - .siconos-build
    - .devel-rules
  needs: ["mambalab:configure"]

mambalab:test:
    variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/mambaenv
      CDASH_SUBMIT: 1
    extends:
      - .siconos-test
      - .devel-rules
    needs: ["mambalab:build"]
    

# -- Jobs executed for MR or main branch only --

# ------ ubuntu 22, numerics only, fclib -------
ubuntu22.04-numerics-fclib:configure:
   variables:
     IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
     CDASH_SUBMIT: 1
     CONF_FILE: $SICONOS_CMAKE_CONF_PATH/numerics_with_fclib.cmake
   extends:
    - .siconos-configure
   needs:
    - job: ubuntu22.04:docker-build
      optional: true

ubuntu22.04-numerics-fclib:build:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
    CDASH_SUBMIT: 1
  extends:
    - .siconos-build
  needs: ["ubuntu22.04-numerics-fclib:configure"]

ubuntu22.04-numerics-fclib:test:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
    CDASH_SUBMIT: 1
  extends:
    - .siconos-test
  needs: ["ubuntu22.04-numerics-fclib:build"]

# ------ ubuntu 22, with mechanisms component -------
# optional (manual)
ubuntu22.04-mechanisms:configure:
   variables:
     IMAGE_NAME: $SICONOS_REGISTRY/sources/opencascade
     CDASH_SUBMIT: 1
     CONF_FILE: $SICONOS_CMAKE_CONF_PATH/with_mechanisms.cmake
   extends:
    - .siconos-configure
   image:
    name: $IMAGE_NAME
    entrypoint: ["/bin/bash"]
   #when: manual
   needs:
    - job: opencascade:docker-build
      optional: true
    
ubuntu22.04-mechanisms:build:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/opencascade
    CDASH_SUBMIT: 1
  extends:
    - .siconos-build
  image:
    name: $IMAGE_NAME
    entrypoint: ["/bin/bash"]
  needs: ["ubuntu22.04-mechanisms:configure"]
  #when: manual

ubuntu22.04-mechanisms:test:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/opencascade
    CDASH_SUBMIT: 1
  extends:
    - .siconos-test
  image:
    name: $IMAGE_NAME
    entrypoint: ["/bin/bash"]
  needs: ["ubuntu22.04-mechanisms:build"]
  #when: manual

    
# ------ debian bookworm, default setup -------
debian-bookworm:configure:
  variables:
     IMAGE_NAME: $SICONOS_REGISTRY/sources/debian-bookworm
     CDASH_SUBMIT: 1
  extends:
    - .siconos-configure
  needs:
    - job: debian-bookworm:docker-build
      optional: true

debian-bookworm:build:
  variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/debian-bookworm
      CDASH_SUBMIT: 1
  extends:
    - .siconos-build
  needs: ["debian-bookworm:configure"]

debian-bookworm:test:
    variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/debian-bookworm
      CDASH_SUBMIT: 1
    extends:
      - .siconos-test
    needs: ["debian-bookworm:build"]

      
# --- fedora 38, default setup ---
fedora-38:configure:
  variables:
     IMAGE_NAME: $SICONOS_REGISTRY/sources/fedora-38
     CDASH_SUBMIT: 1
  extends:
    - .siconos-configure
  needs:
    - job: fedora-38:docker-build
      optional: true

fedora-38:build:
  variables:
    IMAGE_NAME: $SICONOS_REGISTRY/sources/fedora-38
    CDASH_SUBMIT: 1
  extends:
    - .siconos-build
  needs: ["fedora-38:configure"]

fedora-38:test:
    variables:
      IMAGE_NAME: $SICONOS_REGISTRY/sources/fedora-38
      CDASH_SUBMIT: 1
    extends:
    - .siconos-test
    needs: ["fedora-38:build"]


# --- Jobs to install siconos and produce a Docker image "Siconos ready" ---

# Chosen OS for the install is ubuntu 22
# The image is saved in siconos-tutorials (public) registries
# Remark: branch name will be appended to image name.
# Tag will correspond to the commit ref
# siconos:install:
#   variables: 
#     IMAGE_NAME: $SICONOS_REGISTRY/sources/ubuntu22.04
#     RESULT_NAME: $CI_REGISTRY/nonsmooth/siconos-tutorials/siconos
#   extends:
#     - .siconos-install
#     - .devel-rules
#   needs: ["ubuntu22.04-release:build"] 

# The image is saved in siconos-tutorials (public) registries
# Remark: branch name will be appended to image name.
# Tag will correspond to the commit ref
jupyterlab:install:
  variables:
    IMAGE_NAME: siconoslab
    RESULT_NAME: $CI_REGISTRY/nonsmooth/siconos-tutorials/siconoslab
    SICONOS_DOCKER_TARGET: siconoslab
  extends:
    - .siconos-jupyterlab-install
    - .devel-rules
  needs: ["ubuntu22.04-release:build"]

mambalab:install:
    variables:
      IMAGE_NAME: siconoslab-mamba
      RESULT_NAME: $CI_REGISTRY/nonsmooth/siconos-tutorials/siconoslab-mamba
      SICONOS_DOCKER_TARGET: siconoslab
    extends:
      - .siconos-jupyterlab-install
    needs: ["mambalab:build"]

# Job run when a new tag (release) is created.
release_job:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
      when: always
    script:
    - echo "running release_job"
    release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
      tag_name: '$CI_COMMIT_TAG'
      description: '$CI_COMMIT_TAG'

# Start CI in siconos-tutorials, when required
# How? Use [with examples] in your commit message.
# Based on the specific docker image build and saved during siconos:install step.
bridge:examples:
  stage: examples
  trigger: 
    project: nonsmooth/siconos-tutorials
    strategy : depend
    forward :  
      yaml_variables: false
  needs: ["jupyterlab:install"]
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[with examples\]/
    

# --- Creates a new pipeline to build documentation
# Trigger : manual.
# When the job is activated (manual trigger through the web interface),
# it starts a new pipeline, i.e. includes jobs declared in docs/build-doc.yml
generate-doc:
  stage: configure
  trigger:
    include:
      - docs/build-doc.yml
  when: manual

